apiVersion: v1
kind: Service
metadata:
  name: f8k-monitor-mysql
  labels:
    app: f8k-monitor
spec:
  ports:
    - port: 3306
  selector:
    app: f8k-monitor
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: f8k-monitor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: f8k-monitor-mysql
  labels:
    app: f8k-monitor
spec:
  selector:
    matchLabels:
      app: f8k-monitor
      tier: mysql
  template:
    metadata:
      labels:
        app: f8k-monitor
        tier: mysql
    spec:
      containers:
      - image: gcr.io/durable-bond-223609/f8k-monitor-mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: superpassword
        - name: MYSQL_USER
          value: monitor
        - name: MYSQL_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: dev_monevdki
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
