apiVersion: v1
kind: Service
metadata:
  name: f8k-monitor
  labels:
    app: f8k-monitor
spec:
  ports:
    - port: 80
  selector:
    app: f8k-monitor
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: f8k-monitor
  labels:
    app: f8k-monitor
spec:
  selector:
    matchLabels:
      app: f8k-monitor
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: f8k-monitor
        tier: frontend
    spec:
      containers:
      - image: gcr.io/durable-bond-223609/f8k-monitor:latest
        name: f8k-monitor
        env:
        - name: ENVIRONMENT
          value: production
        - name: MYSQL_HOST
          value: f8k-monitor-mysql.default.svc.cluster.local
        - name: MYSQL_USER
          value: monitor
        - name: MYSQL_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: dev_monevdki
        ports:
        - containerPort: 80
          name: f8k-monitor
